#!/bin/bash

# Script Name:                  Ops Challenge 2 class 3
# Author:                       Steve Cherewaty
# Date of latest revision:      02/21/2024
# Purpose:                      Run a function
# Resources:  https://superuser.com/questions/134364/how-can-i-invoke-a-function-in-bash-shell-script

# Declaration of variables



# Declare Functions

print_message() {
    echo "var=$(last)"
}


# Main

# echo $greeting
# greeting="This is the login history"
# echo $greeting

# Invoking 
print_message
print_message
print_message

# End

echo "This is the login history"